### PR TITLE
Use `he` for robust HTML entity encoding/decoding

### PR DESCRIPTION
**Pull request by mathiasbynens**
_ent_ has [several open issues](https://github.com/substack/node-ent/issues/created_by/mathiasbynens?state=open) that are not present in [_he_](http://mths.be/he).

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Ping @ecto?

**Comment by ecto** [comment]
Sorry, hadn't seen this. `he` looks great and seems to handle many edge cases. I'll push this.

Thanks!

**Comment by ecto** [comment]
Pushed @ 0.3.0

**Comment by mathiasbynens** [comment]
Thanks!

**Pull request merged**
